spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alpha_bank
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /alpha-bank
  port: 8080